language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '8.0'

matrix:
  fast_finish: true

before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run --config=phpspec.yml --no-interaction
